### ISSUE TITLE
Can treeSeg be used with categorical data with >2 categories?

### ISSUE THREAD

**Issue by flashton2003** [merlebehr/treeSeg#1]
I was just wondering if treeSeg can be used with categorical data which has >2 categories?

The documentation for the function in R mentions binary and continuous, but I'm not sure about categorical with >2 categories.

**Comment by ansariazim** [comment]
Not yet, but you can convert your phenotypes into multiple binary categories (one category vs. all others) and run treeSeg on those binary categories.
